import type { Metadata } from "next";
import "./globals.css";
import Nav from "./_components/nav";
import Avatar from "./_components/avatar";
import Action from "./_components/action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Nav />
          <div className="w-full">
            {/* Nav and Search */}
            <div className="sticky top-0 flex px-2 py-2 justify-between  border border-gray-800">
              <div className="flex">
                <Action className="w-8 h-8 bg-red-200">Back</Action>
                <Action className="w-8 h-8 bg-red-200">Fwd</Action>
              </div>
              <input
                type="search"
                placeholder="Search people, policies..."
                className="bg-gray-700 w-full max-w-[600px] px-2"
              />
              <Avatar
                employee={{ name: "Test User" }}
                className="justify-end shrink-0"
              />
            </div>
            <div className="p-8">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
